# Generated by Django 4.2 on 2024-09-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Yuen Long', 'Yuen Long'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Poo', 'Sham Shui Poo'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Tai Poo', 'Tai Poo'), ('Sha Tin', 'Sha Tin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Kowloon City', 'Kowloon City'), ('Eastern', 'Eastern'), ('Central and Western', 'Central and Western'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai')], max_length=50),
        ),
    ]
